- CHANGELOG.md
- OneBlink.SDK.Tests/FormsClientTests.cs
- OneBlink.SDK/FormsClient.cs
- OneBlink.SDK/OneBlink.SDK.csproj
- OneBlink.SDK/OneBlinkPdfHttpClient.cs
- OneBlink.SDK/PdfClient.cs
- docs/deployment.md
- docs/forms-client.md
Reverts blinkmobile/oneblink-sdk-dotnet#11
> Revert "ON-4342 # Added FormsClient.GetDraftSubmission()"

- CHANGELOG.md
- OneBlink.SDK/models/Form.cs
- OneBlink.SDK/models/FormApprovalCannedResponse.cs
- OneBlink.SDK/models/FormApprovalConfiguration.cs
- OneBlink.SDK/models/FormSubmissionApproval.cs
-   `cannedResponseKey` to `FormSubmissionApproval`
> ON-24720 # Added -   `FormApprovalCannedResponse` class

- CHANGELOG.md
- OneBlink.SDK/models/FormElement.cs
Undecided if this is really useful or not. Happy if we agree to won't do it and close the PR
> ON-37370 # Added new form element config

- CHANGELOG.md
- OneBlink.SDK/models/DeveloperKey.cs
> ON-41184 # Added customerSecretId to DeveloperKey

- docs/README.md
- docs/approvals-client.md
- docs/data-manager-client.md
- docs/forms-client.md
- docs/pdf-client.md
> ON-43626 # Added docs for submission data developer keys

- CHANGELOG.md
- OneBlink.SDK/models/Form.cs
- OneBlink.SDK/models/FormEnableSubmission.cs
- docs/models/Form.md
> ON-43906 # Add `enableSubmission` to `Form`

- CHANGELOG.md
- OneBlink.SDK/models/FormExternalIdGenerationConfiguration.cs
> ON-44406 # Added `startingAutoIncrement` to `FormExternalIdGenerationConfiguration`

- CHANGELOG.md
- OneBlink.SDK/models/FormSubmissionEvent.cs
- OneBlink.SDK/models/FormSubmissionEventConfiguration.cs
> ON-44715 # Added `nylasGrantId` and `nylasConfigurationId` to `FormSubmissionEventConfiguration`

- CHANGELOG.md
- OneBlink.SDK/FormsAppsClient.cs
- OneBlink.SDK/models/Role.cs
> ON-44640 # Removed FormsAppsClient.UpdateStyles()

- CHANGELOG.md
- OneBlink.SDK/models/FormApprovalFlowInstanceStep.cs
- OneBlink.SDK/models/FormApprovalFlowStepBase.cs
- OneBlink.SDK/models/FormApprovalStep.cs
> ON-44920 # Added nodes to approval steps

- CHANGELOG.md
- OneBlink.SDK/models/FormsAppBase.cs
> ON-45030 # Added cachingStrategies to FormsAppBase

- CHANGELOG.md
- OneBlink.SDK/FormsClient.cs
- OneBlink.SDK/OrganisationsClient.cs
> ON-45358 # Headers not being escaped when uploading to s3

- CHANGELOG.md
- OneBlink.SDK.Tests/FormsAppEnvironmentsClientTests.cs
- OneBlink.SDK/models/Form.cs
- OneBlink.SDK/models/FormsAppEnvironment.cs
> ON-45970 # Added `isArchived` to Forms

- CHANGELOG.md
- OneBlink.SDK/models/FormSubmissionEventConfiguration.cs
> ON-46778 # Added properties support SharePoint Store Files form workflow event

- CHANGELOG.md
- OneBlink.SDK/models/Form.cs
- OneBlink.SDK/models/FormCustomPDF.cs
- OneBlink.SDK/models/FormMigrationOptions.cs
- OneBlink.SDK/models/FormSubmissionEventConfigurationMapping.cs
- OneBlink.SDK/models/FormsAppEnvironmentCloneOptions.cs
- OneBlink.SDK/models/PDFConfiguration.cs
- docs/models/Form.md
> ON-46920 # Added `customPDFs` to Forms

- CHANGELOG.md
- OneBlink.SDK.Tests/PdfClientTests.cs
- OneBlink.SDK/PdfClient.cs
- OneBlink.SDK/models/GetSubmissionPdfRequest.cs
> ON-47258 # Changed PdfClient.GetSubmissionPdf parameters

- .github/workflows/build.yml
> Bump github/codeql-action/upload-sarif action version

- CHANGELOG.md
- OneBlink.SDK/FormsClient.cs
>  ON-47635 # Fixed FormsClient.Get() using legacy endpoint

- CHANGELOG.md
- OneBlink.SDK/models/PDFConfiguration.cs
> ON-47531 # Added `isCustomPdfEditable` to `PDFConfiguration`

- CHANGELOG.md
- OneBlink.SDK/models/Form.cs
- OneBlink.SDK/models/FormElement.cs
Closes: OB-2421
- When reviewing tests, attempt to identify missing edge cases that may be relevant to …
> OB-2413 # Added `isDisplayingAddressInformation` to `FormElement`

- CHANGELOG.md
- OneBlink.SDK/models/Form.cs
> AP-2537 # Removed sharepointIntegrationEntraApplicationId

- CHANGELOG.md
- OneBlink.SDK/models/Form.cs
> AP-2661 # Added pointAddressV3EnvironmentId to Form class

- OneBlink.SDK/models/GraphicType.cs
> ON-48077 # Add `id` to `GraphicType`

- OneBlink.SDK/models/DrawingTool.cs
- OneBlink.SDK/models/GraphicAttributeOption.cs
> ON-48090 # Rename `graphicTypes` to `graphicAttributeOptions`

- CHANGELOG.md
- OneBlink.SDK/models/FormsAppBase.cs
> MS-182 # Add `googleAnalyticsTagId` to `FormsAppBase`

- CHANGELOG.md
- OneBlink.SDK/models/JWTPayload.cs
> MS-196 # Add Additional attributes to `RawJWTPayload`

- CHANGELOG.md
- OneBlink.SDK/FormsAppsClient.cs
- OneBlink.SDK/models/FormSubmission.cs
> MS-217 # added additional attributes to `FormSubmissionUser`

- CHANGELOG.md
- OneBlink.SDK/models/FormElement.cs
> ap-3209 # Added `requiresConfirmation` to Email Element

- CHANGELOG.md
- OneBlink.SDK/models/DynamicListOption.cs
- OneBlink.SDK/models/FormSubmissionWebhookPayload.cs
> AP-3381 # Added DynamicListOption and FormSubmissionWebhookPayload classes

- CHANGELOG.md
- OneBlink.SDK/models/FormsAppEnvironment.cs
> MS-267 # Add `customHostname` to `FormsAppEnvironment`

- CHANGELOG.md
- OneBlink.SDK/models/Form.cs
- OneBlink.SDK/models/FormFooter.cs
> ap-3893 # Added footer to form

- CHANGELOG.md
- OneBlink.SDK/models/Form.cs
- OneBlink.SDK/models/FormsAppFooter.cs
- OneBlink.SDK/models/FormsListStyles.cs
> AP-4047 # Changed footer to forms apps

- CHANGELOG.md
- OneBlink.SDK.Tests/FormsClientTests.cs
- OneBlink.SDK/models/FormSubmissionEvent.cs
- OneBlink.SDK/models/FormSubmissionEventConfiguration.cs
- OneBlink.SDK/models/FormSubmissionEventConfigurationMapping.cs
> ap-4106 # Added Good To Go update asset submission event

- CHANGELOG.md
- OneBlink.SDK/FormsClient.cs
- OneBlink.SDK/OneBlinkApiClient.cs
- OneBlink.SDK/OrganisationsClient.cs
> AP-4161 # Removed encoding of values in request headers

- CHANGELOG.md
- OneBlink.SDK/FormsClient.cs
- OneBlink.SDK/OrganisationsClient.cs
Reverts oneblink/sdk-dotnet#382
> Revert "AP-4161 # Removed encoding of values in request headers"

- CHANGELOG.md
- OneBlink.SDK/models/FormPostSubmissionReceipt.cs
> AP-4491 # Added allowAttachmentsDownload to FormPostSubmissionReceipt class 

- CHANGELOG.md
- OneBlink.SDK/FormsClient.cs
- OneBlink.SDK/models/AttachmentData.cs
> AP-4585 # Added path to AttachmentData
